appencuesta/urls.py
 # -- coding: utf-8 --
from django.conf.urls import url
from .campania_view import CampaniaCrear, CampaniaDetalle
from .viewencuesta import  EncuestaBorrar, EncuestaDetalle, EncuestaConfirmaAlta, EncuestaListar
from .viewencuestapasos import EncuestaCrear,EncuestaProcedimiento, EncuestaPerfil, EncuestaCalidad
from .viewparada_prompt import ParadaPrompt

from .viewlogin import user_login, user_logout
from .views import index
from django.contrib.auth.decorators import login_required

app_name="appencuesta" #namespace

urlpatterns = [
    url(r'^$', login_required(index), name='index'),
    #url(r'^clientes/$', login_required(ClienteListar.as_view()), name='cliente_listar'),
    url(r'^campania/crear/$', CampaniaCrear.as_view(), name='campania_crear'),
    url(r'^campania/(?P<pk>\d+)/$', CampaniaDetalle.as_view(), name='campania_detalle'),
    #url(r'^clientes/(?P<pk>\d+)/modificar/$', login_required(ClienteModificar.as_view()), name='cliente_modificar'),
    #url(r'^clientes/(?P<pk>\d+)/borrar/$', login_required(ClienteBorrar.as_view()), name='cliente_borrar'),

    #Login y logout
    url(r'^login/$', user_login, name='login'),
    url(r'^logout/$', user_logout, name='logout'),

    url(r'^encuesta/(?P<pk>\d+)/borrar/$', EncuestaBorrar.as_view(), name='encuesta_borrar'),

    #para texto: (?P<post_id>[\w-]+)
    #para números: (?P<pk>\d+)

    url(r'^encuesta/$', EncuestaListar.as_view(), name='encuesta_listar'),
    url(r'^encuesta/(?P<pk>\d+)/$', EncuestaDetalle.as_view(), name='encuesta_detalle'),
	url(r'^encuesta/(?P<pk>\d+)/confirmaalta$', EncuestaConfirmaAlta.as_view(), name='encuesta_confirma_alta'),
    #paso1. datos sobre el procedimiento de encuesta
    url(r'^encuesta/crear/$', EncuestaCrear.as_view(), name='encuesta_crear'),
    #datos similares al alta
    url(r'^encuesta/(?P<pk>\d+)/procedimiento/$', EncuestaProcedimiento.as_view(), name='encuesta_procedimiento'),
    #paso2. perfil del usuario
    url(r'^encuesta/(?P<pk>\d+)/perfil/$', EncuestaPerfil.as_view(), name='encuesta_perfil'),
    #paso3. Calidad del servicio
    url(r'^encuesta/(?P<pk>\d+)/calidad/$', EncuestaCalidad.as_view(), name='encuesta_calidad'),
    #seleccion de paradas
    url(r'^paradaprompt/$', ParadaPrompt.as_view(), name='parada_prompt'),
]

encuesta/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url
from django.contrib import admin
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^appencuesta/', include('appencuesta.urls')),
]

appencuesta/models.py
# -- coding: utf-8 --
import uuid
from django.contrib.auth.models import User
from django.db import models
from datetime import date, time, datetime
from django.utils.encoding import python_2_unicode_compatible
from django.db.models.query import QuerySet

""" constantes """
#momento de la encuesta
ANTES_ASCENDER = 'AA'
LUEGO_DESCENDER = 'LD'

PARADA = 'P' #tipos de Lugares.parada

class ActivosQuerySet(QuerySet):
    def delete(self):
        self.update(activo=False)

class AdministrarActivos(models.Manager):
    def activo(self):
        return self.model.objects.filter(activo=True)

    def get_queryset(self):
        return ActivosQuerySet(self.model, using=self._db)

@python_2_unicode_compatible
class Numerador (models.Model):
	nombre = models.CharField(max_length=30, blank='true',unique=True)
	ultimo_valor = models.IntegerField(default=0)
	def __str__(self):
		return self.nombre

#from nqnmovilutiles import sigNumero,completarConCeros #Como usa Numerador, lo importo después de que existe en model
""" signumero y completar con ceros deben moverse a un archirvo nqnmovilutiles"""
def sigNumero(nombreNumerador):
	try:
		n = Numerador.objects.get(nombre=nombreNumerador)
	except Numerador.DoesNotExist:
		#Si no existe en la BD, lo creo
		n = Numerador(nombre=nombreNumerador, ultimo_valor = 1)
		n.save()
		return n.ultimo_valor
	else:
		#si existe, incremento el valor, lo guardo y lo retorno
		n.ultimo_valor += 1
		n.save()
		return n.ultimo_valor

def completarConCeros( numero, longitud):
	numerotxt = str(numero)
	return numerotxt.zfill(longitud)


@python_2_unicode_compatible
class Campania (models.Model):
  descripcion = models.CharField('Descripción',max_length=100)
  fecha_inicio = models.DateField('Fecha de inicio', default=date.today)
  fecha_fin = models.DateField('Fecha de fin')
  def __str__(self):
    return self.descripcion
  class Meta:
    verbose_name = "Campaña"
    verbose_name_plural = "Campañas"

#@python_2_unicode_compatible
class Encuestador (models.Model):
  usuario = models.ForeignKey(User)
  activo = models.BooleanField('Encuestador activo',default=True)
  def __str__(self):
    return self.usuario.get_full_name()#self.usuario.first_name
  class Meta:
    verbose_name = "Encuestador"
    verbose_name_plural = "Encuestadores"
  def delete(self):
    self.activo = False
    self.save()

@python_2_unicode_compatible
class Parada (models.Model):
  numero = models.CharField('Número',max_length=10)
  def __str__(self):
    return self.numero
  class Meta:
    verbose_name = "Parada"
    verbose_name_plural = "Paradas"

@python_2_unicode_compatible
class Linea (models.Model):
  nombre = models.CharField('nombre de la línea',max_length=10)
  def __str__(self):
    return self.nombre

@python_2_unicode_compatible
class Lugar (models.Model):
  #tipo de lugar
  ZONA= 'Z'
  HITO = 'H'
  PARADA = 'P'
  CALLE = 'C'
  BARRIO = 'B'
  TIPO_LUGAR = (
    (ZONA, 'Zona'),
    (HITO, 'Hito'),
    (PARADA, 'Parada'),
    (CALLE, 'Calle'),
    (BARRIO, 'Barrio')
  )
  tipo = models.CharField('Tipo de lugar',max_length=1, choices=TIPO_LUGAR, blank='true')
  nombre = models.CharField('Nombre del lugar',max_length=100)
  def __str__(self):
    return self.nombre
  class Meta:
    verbose_name = "Lugar"
    verbose_name_plural = "Lugares"
@python_2_unicode_compatible
class Motivo (models.Model):
  nombre = models.CharField('nombre del motivo',max_length=100)
  def __str__(self):
    return self.nombre

@python_2_unicode_compatible
class Encuesta (models.Model):
  #momento de la encuesta
  ANTES_ASCENDER = 'AA'
  LUEGO_DESCENDER = 'LD'
  MOMENTO = (
    (ANTES_ASCENDER, 'antes de ascender'),
    (LUEGO_DESCENDER, 'luego de descender'),
  )
  #sexo
  FEMENINO = 'F'
  MASCULINO = 'M'
  SEXO = (
    (FEMENINO, 'Femenino'),
    (MASCULINO, 'Masculino'),
  )
  #rango de edad
  JOVEN = 'JO'
  ADULTO = 'A1'
  ADULTO_MAYOR = 'AM'
  RANGO_EDAD = (
    (JOVEN,'Jóven (18-25 años)'),
    (ADULTO,'Adulto (25-60 años)'),
    (ADULTO_MAYOR,'Adulto mayor (más de 60 años)'),
  )
  #tipo de lugar
  ZONA= 'Z'
  HITO = 'H'
  PARADA = 'P'
  TIPO_LUGAR = (
    (ZONA, 'Zona'),
    (HITO, 'Hito'),
    (PARADA, 'Parada'),
  )

  #datos sobre el procedimiento de encuesta
  #nousar esto: id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
  referencia = models.CharField('Número de encuesta',max_length=10,blank='true') #autoincremental
  encuestador = models.ForeignKey('Encuestador',Encuestador, null='true')
  parada_encuesta = models.ForeignKey(Parada,verbose_name='Parada', null='true', on_delete= models.PROTECT)
  cargaonline = models.BooleanField('Encuesta cargada en línea',default=True)
  dia_realizada = models.DateField('fecha de realización', default=date.today)
  hora_realizada = models.TimeField('hora de realización', default= time(16, 00))
  hora_inicio = models.DateTimeField(blank = 'true', null = 'true')
  hora_fin = models.DateTimeField(blank = 'true', null = 'true')
  momento = models.CharField('Momento de la encuesta',max_length=2, choices=MOMENTO, default= ANTES_ASCENDER)
  #perfil del usuario
  sexo = models.CharField('1.a. Sexo',max_length=1, choices=SEXO)
  rango_edad = models.CharField('1.b. Rango de edad',max_length=2, choices=RANGO_EDAD)
  #origen del viaje
  #parahacer:ocultar lugar y parada tanto de origen como destino o dejar que lo carguen en blanco
  origen_lugar = models.ForeignKey(Lugar, related_name='encuesta_origen_lugar', null='true', blank='true', on_delete= models.PROTECT)

  origen_motivo = models.ForeignKey(Motivo,verbose_name='2.a. Motivo del viaje. Desde',related_name='encuesta_origen_motivo', null='true', on_delete= models.PROTECT)
  origen_parada =  models.CharField('Parada de origen (opcional)',max_length=10, blank='true') #solo se carga si el tipo de lugar es parada
  #destino del viaje
  destino_lugar = models.ForeignKey(Lugar,related_name='encuesta_destino_lugar', null='true', blank='true', on_delete= models.PROTECT)
  destino_motivo = models.ForeignKey(Motivo,verbose_name='2.b. Motivo del viaje. Hacia',related_name='encuesta_destino_motivo', null='true', on_delete= models.PROTECT)
  destino_parada =  models.CharField('Parada de destino (opcional)',max_length=10, blank='true') #solo se carga si el tipo de lugar es parada
  #detalles del viaje
  #veces por semana
  TODOS_LOS_DIAS = 'TODOS'
  TRES_O_MAS = '3OMAS'
  MENOS_DE_TRES = 'MENOS3'
  VECES_SEMANA = (
    (TODOS_LOS_DIAS, 'Todos los días'),
    (TRES_O_MAS, 'Tres o más'),
    (MENOS_DE_TRES, 'Menos de tres'),
  )
  veces_semana = models.CharField('3.a. Veces por semana en que realiza este viaje',max_length=6, choices=VECES_SEMANA)
  #veces por día
  DOS_O_MAS  = '2OMAS'
  MENOS_DE_DOS = 'MENOS2'
  VECES_DIA = (
    (DOS_O_MAS, 'Dos o más'),
    (MENOS_DE_DOS, 'Menos de dos'),
  )
  veces_dia = models.CharField('3.b. Veces por día en que realiza este viaje',max_length=6, choices=VECES_DIA)
  #otros medios de transporte
  NO_OTRO_MEDIO = 'NO'
  OTRA_LINEA = 'OLINEA'
  AUTO = 'AUTO'
  TAXI_REMIS = 'TAXREM'
  OTRO = 'OTRO'
  OTRO_MEDIO = (
    (NO_OTRO_MEDIO,'No'),
    (OTRA_LINEA,'Otra línea'),
    (AUTO,'Automóvil'),
    (TAXI_REMIS,'Taxi o Remis'),
    (OTRO,'Otro medio'),
  )
  otro_medio = models.CharField('4. Para completar el viaje ¿Usa otro medio de transporte?',max_length=6, choices=OTRO_MEDIO)
  linea = models.ForeignKey(Linea,verbose_name='5. ¿En qué línea de transporte suele viajar?', null='true', on_delete= models.PROTECT)
  #calidad del servicio
  MUY_BUENO = 'MB'
  BUENO = 'BU'
  REGULAR = 'RE'
  MALO = 'MA'
  NS_NC = 'NS'
  CALIFICA_CALIDAD = (
    (MUY_BUENO, 'muy bueno'),
    (BUENO, 'bueno'),
    (REGULAR, 'regular'),
    (MALO, 'malo'),
    (NS_NC, 'Ns/Nc'),
  )
  estado_unidad =  models.CharField('6.a. Estado general de las unidades',max_length=2, choices=CALIFICA_CALIDAD, default = NS_NC)
  comodidad =  models.CharField('6.b. Comodidad con la que viaja',max_length=2, choices=CALIFICA_CALIDAD, default = NS_NC)
  higiene_unidad =  models.CharField('6.c. Higiene de las unidadades',max_length=2, choices=CALIFICA_CALIDAD, default = NS_NC)
  trato_choferes =  models.CharField('7.a. Nivel de trato y atención recibida por los choferes',max_length=2, choices=CALIFICA_CALIDAD, default = NS_NC)
  conduccion_choferes =  models.CharField('7.b. Desempeño de los choferes en la conducción',max_length=2, choices=CALIFICA_CALIDAD, default = NS_NC)
  info_choferes =  models.CharField('7.c. Nivel de información del sistema de transporte de los choferes?',max_length=2, choices=CALIFICA_CALIDAD, default = NS_NC)
  #Interes en servicios anexos
  SI = 'SI'
  NO = 'NO'
  NO_ME_INTERESA = 'NI'
  NO_LO_CONOZCO = 'NC'

  INTERES_SERVICIOS_ANEXOS = (
    (SI,'Si'),
    (NO,'No'),
    (NO_LO_CONOZCO,'No. No lo conozco'),
  )

  #medios de información de transporte
  WEB_CUANDOPASA = 'WC'
  WEB_MUNICIPAL = 'WM'
  CONSULTAS_TELEFONICAS = 'CT'
  MENSAJE_TEXTO = 'MT'
  CARTELES_INTELIGENTES ='CI'
  APP_CEL_CUANDO_PASA = 'CP'

  USA_MEDIOS_INFORMACION = (
    (SI,'Si'),
    (NO,'No'),
    (NO_ME_INTERESA,'No. No estoy interesado/a'),
    (NO_LO_CONOZCO,'No. No lo conozco'),
    (WEB_CUANDOPASA,'Si. Página web de cuandopasa.com'),
    (WEB_MUNICIPAL,'Si. Página web de la Municipalidad'),
    (CONSULTAS_TELEFONICAS,'Si. Consultas telefónicas'),
    (MENSAJE_TEXTO,'Si. Mensaje de texto'),
    (CARTELES_INTELIGENTES,'Si. Carteles de información LED'),
 )
  usa_medio_informacion = models.CharField('8. ¿Utiliza algún medio de información de transporte?',max_length=2, choices=USA_MEDIOS_INFORMACION, default = NO_LO_CONOZCO)
  usa_trasbordo = models.CharField('9. ¿Utiliza el servicio de trasbordo?',max_length=2, choices=INTERES_SERVICIOS_ANEXOS, default = NO)

  #paraHacer:tarjeta sube
  #beneficios tarjeta sube
  BENEF_SUBE_NO = 'BS_NO'
  BENEF_SUBE_SI_ANSES = 'BS_AN'
  BENEF_SUBE_SI_ESCOLAR = 'BS_ES'
  BENEF_SUBE_SI_UNIVERSITARIO = 'BS_UN'
  BENEF_SUBE_SI_JUCAID = 'BS_JU'
  SUBE_BENEFICIOS = {
    (BENEF_SUBE_NO,'No'),
    (SI,'Si'),

appencuesta/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
  return HttpResponse("Hola")

templates/appencuesta/campania_detail.html
{% extends "marco.html" %}
{% block content %}

<p>Empresa: {{ campania.descripcion }}</p>
<p>Empresa: {{ campania.fecha_inicio }}</p>
<p>Empresa: {{ campania.fecha_fin }}</p>

{% endblock content %}

templates/appencuesta/campania_form.html
{% extends "marco.html" %}
{% block content %}
{% load crispy_forms_tags %}
{% crispy form %}  
{% endblock content %}

templates/appencuesta/encuesta_confirm_create.html
{% extends "marco.html" %}
{% block content %}
<h1>Encuesta {{ encuesta }} creada correctamente</h1>
<p>Encuestador: {{ encuesta.encuestador.usuario.username }}</p>
<a href="{% url "appencuesta:encuesta_listar"  %}">Encuestas</a>
{% endblock content %}

templates/appencuesta/encuesta_confirm_delete.html
{% extends "marco.html" %}
{% block content %}
	{{estado}}
<form method="post">{% csrf_token %}
    Está seguro de eliminar "{{ object }}" ?
    <input type="submit" value="Eliminar" />
</form>
{% endblock content %}

templates/appencuesta/encuesta_detail.html
{% extends "marco.html" %}
{% block content %}
<h1>Encuesta {{ encuesta}} creada correctamente</h1>

<p>Usuario: {{ encuesta.encuestador.usuario.username }}</p>
<p>Realizada: {{encuesta.dia_realizada}} {{encuesta.hora_realizada}}</p>
<a href="{% url "appencuesta:encuesta_listar"  %}">Encuestas</a>
{% endblock content %}

templates/appencuesta/encuesta_form.html
{% extends "marco.html" %}
{% block content %}
{% load crispy_forms_tags %}
{% crispy form %}
{% endblock content %}

templates/appencuesta/encuesta_list.html
{% extends "marco.html" %}
{% load staticfiles %}
{% block content %}
<div class="container">
	<h2>Encuestas</h2>
		<form method="get" action="/appencuesta/encuesta/">
		<p><label for="id_filtro_num">Número de encuesta:</label>
		<input type="text" name="filtro_num" id="id_filtro_num" value="{{ filtro_num }}" /></p>
		<p><label for="id_filtro_ape">Apellido del encuestador:</label>
		<input type="text" name="filtro_ape" id="id_filtro_ape" value="{{ filtro_ape }}" /></p>
		<p><label for="id_filtro_ape">Nombre del encuestador:</label>
		<input type="text" name="filtro_nom" id="id_filtro_nom" value="{{ filtro_nom }}" />	</p>
		<input type="submit" value="Buscar" />
		<input type="button" value="Limpiar filtros" onclick='javascript: LimpiarFiltros();'/>
		</form>
  <table class="table table-hover">
    <thead>
      <tr>
		    <th></th>
		    <th></th>
				<th>Número</th>
				<th>Encuestador</th>
				<th>Parada de encuesta</th>
				<th>Día</th>
				<th>Hora</th>
				<th>Estado</th>

      </tr>
    </thead>
    <tbody>
    {% for encuesta in encuesta_list %}
	<tr>
    <td><a href="{% url "appencuesta:encuesta_procedimiento" encuesta.id %}" ><img src= "{% static "images/accion_modificar.png"%}" data-toggle="tooltip" data-placement="top" title="Modificar" alt= "Modificar"></a></td>
    <td><a href="{% url "appencuesta:encuesta_borrar" encuesta.id %}"><img src= "{% static "images/accion_borrar.png"%}" data-toggle="tooltip" data-placement="top" title="Borrar" alt= "Borrar"></a></td>
		<td>{{ encuesta.referencia  }}</td>
		<td>{{ encuesta.encuestador  }}</td>
		<td>{{ encuesta.parada_encuesta }}</td>
		<td>{{ encuesta.dia_realizada }}</td>
		<td>{{ encuesta.hora_realizada }}</td>
		<th>{{ encuesta.estado }}</th>
	</tr>
    {% endfor %}
    </tbody>
  </table>
  {% if is_paginated %}
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="/appencuesta/encuesta?q={{query}}&page={{ page_obj.previous_page_number }}">anterior</a>
              {% endif %}
              <span class="page-current">
                  Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="/appencuesta/encuesta?q={{query}}&page={{ page_obj.next_page_number }}">siguiente</a>
              {% endif %}
          </span>
      </div>
  {% endif %}
</div>
<a href="{% url "appencuesta:encuesta_crear"  %}"><img src= "{% static "images/accion_alta.png"%}" data-toggle="tooltip" data-placement="top" title="Agregar" alt="Agregar"></a>

<script type="text/javascript">
  function LimpiarFiltros(){
    $("[id^='id_filtro']").val('')
  }
</script>
{% endblock content %}

templates/appencuesta/login.html
<!DOCTYPE hmtl>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Logín a NQN Movilidad</title>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/signin.css' %}">
  </head>
  <body>
        <form id="login_form" method="post" action="/appencuesta/login/" class="form-signin">
          <div class="row">
            <div>
              <div class="text-center">
                <img class="img-responsive" src= "{% static "images/logo_nqn_movilidad.png"%}" alt="Logotipo de NQN Movilidad">
              </div>
            </div>
          </div>
          <div class="row">
            <div>
              <h3 class="form-signin-heading">Por favor ingrese sus credenciales</h3>
      		    {% if mensaje  %}
      		    <div class="alert alert-danger" role="alert">
      		      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
      			    <span class="sr-only">¡Atención!</span>{{mensaje}}
      		    </div>
              {% endif %}
              <label for="username" class="sr-only">Usuario</label>
              <input type="text" id="username" name="username" class="form-control" placeholder="Usuario" required autofocus>
              <label for="password" class="sr-only">Clave</label>
              <input type="password" id="password" name="password" class="form-control" placeholder="Clave" required>
              <div class="checkbox">
              </div>
              <button class="btn btn-lg btn-primary btn-block" type="submit">Ingresar</button>
          </div>
        </form>
  </body>
<html>

templates/appencuesta/parada_prompt.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <title>NQN Movilidad</title>
    <head>
        <title>NQN Movilidad</title>
  		<!--<meta charset="utf-8">-->
  		<meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
		<link href='https://fonts.googleapis.com/css?family=Dosis:500&effect=outline' rel='stylesheet' type='text/css'>
    </head>
<div class="container">
	<h2>Selección de Parada</h2>
		<form method="get" action="/appencuesta/paradaprompt/">
		<p><label for="id_q">Filtro (Número):</label>
		<input type="text" name="q" id="id_q" value="{{ query }}" />
		<input type="submit" value="Buscar" /></p>
		</form>
  <table class="table table-hover">
    <thead>
      <tr>
		<th></th>
        <th>Número</th>
      </tr>
    </thead>
    <tbody>
    {% for parada in parada_list %}
	<tr>
    	<td><a href="#" onclick="sendValues({{ parada.id }});" ><img src= "{% static "images/accion_elegir.png"%}" data-toggle="tooltip" data-placement="top" title="Seleccionar" alt= "Seleccionar"></a></td>
		<td>{{ parada.numero }}</td>
	</tr>
    {% endfor %}
    </tbody>
  </table>
  {% if is_paginated %}
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="/appencuesta/paradaprompt?q={{query}}&page={{ page_obj.previous_page_number }}">anterior</a>
              {% endif %}
              <span class="page-current">
                  Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="/appencuesta/paradaprompt?q={{query}}&page={{ page_obj.next_page_number }}">siguiente</a>
              {% endif %}
          </span>
      </div>
  {% endif %}
</div>

<script type="text/javascript">
 function sendValues(idparada){
 opener.window.document.getElementById('id_parada_encuesta').value = idparada

 window.close();
 }
</script>