appencuesta/urls.py
 # -- coding: utf-8 --
from django.conf.urls import url
from .campania_view import CampaniaCrear, CampaniaDetalle
from .viewencuesta import  EncuestaBorrar, EncuestaDetalle, EncuestaConfirmaAlta, EncuestaListar
from .viewencuestapasos import EncuestaCrear,EncuestaProcedimiento, EncuestaPerfil, EncuestaCalidad
from .viewparada_prompt import ParadaPrompt

from .viewlogin import user_login, user_logout
from .views import index
from django.contrib.auth.decorators import login_required

app_name="appencuesta" #namespace

urlpatterns = [
    url(r'^$', login_required(index), name='index'),
    #url(r'^clientes/$', login_required(ClienteListar.as_view()), name='cliente_listar'),
    url(r'^campania/crear/$', CampaniaCrear.as_view(), name='campania_crear'),
    url(r'^campania/(?P<pk>\d+)/$', CampaniaDetalle.as_view(), name='campania_detalle'),
    #url(r'^clientes/(?P<pk>\d+)/modificar/$', login_required(ClienteModificar.as_view()), name='cliente_modificar'),
    #url(r'^clientes/(?P<pk>\d+)/borrar/$', login_required(ClienteBorrar.as_view()), name='cliente_borrar'),

    #Login y logout
    url(r'^login/$', user_login, name='login'),
    url(r'^logout/$', user_logout, name='logout'),

    url(r'^encuesta/(?P<pk>\d+)/borrar/$', EncuestaBorrar.as_view(), name='encuesta_borrar'),

    #para texto: (?P<post_id>[\w-]+)
    #para números: (?P<pk>\d+)

    url(r'^encuesta/$', EncuestaListar.as_view(), name='encuesta_listar'),
    url(r'^encuesta/(?P<pk>\d+)/$', EncuestaDetalle.as_view(), name='encuesta_detalle'),
	url(r'^encuesta/(?P<pk>\d+)/confirmaalta$', EncuestaConfirmaAlta.as_view(), name='encuesta_confirma_alta'),
    #paso1. datos sobre el procedimiento de encuesta
    url(r'^encuesta/crear/$', EncuestaCrear.as_view(), name='encuesta_crear'),
    #datos similares al alta
    url(r'^encuesta/(?P<pk>\d+)/procedimiento/$', EncuestaProcedimiento.as_view(), name='encuesta_procedimiento'),
    #paso2. perfil del usuario
    url(r'^encuesta/(?P<pk>\d+)/perfil/$', EncuestaPerfil.as_view(), name='encuesta_perfil'),
    #paso3. Calidad del servicio
    url(r'^encuesta/(?P<pk>\d+)/calidad/$', EncuestaCalidad.as_view(), name='encuesta_calidad'),
    #seleccion de paradas
    url(r'^paradaprompt/$', ParadaPrompt.as_view(), name='parada_prompt'),
]

encuesta/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url
from django.contrib import admin
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^appencuesta/', include('appencuesta.urls')),
]

templates/marco.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <title>NQN Movilidad</title>
  		  <!--<meta charset="utf-8">-->
  		  <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
		    <link href='//fonts.googleapis.com/css?family=Dosis:500&effect=outline' rel='stylesheet' type='text/css'>

        <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
    		<script src="{% static 'js/locales/bootstrap-datepicker.es.js'%}" charset="UTF-8"></script>
    	  <link rel="stylesheet" href="{% static 'css/datepicker.css' %}">

    </head>
    <body>
		<!-- logo y cerrar sesion -->
    <!-- Stack the columns on mobile by making one full-width and the other half-width -->
  	<div class="row">
          <div class="col-xs-3 col-md-3 col -sm-1">
    	      <!--logo -->
  	      <a href="{% url "appencuesta:encuesta_listar"  %}"><img class="img-responsive" src= "{% static "images/logo_nqn_movilidad.png"%}" alt="Logotipo de NQN Movilidad"></a>
          </div>
          <div class="col-xs-8 col-md-8"></div>
          <div class="col-lg-1">
              <p class="text-left"><strong>{{ user.username }}</strong></p>
              <p><a href="{% url "appencuesta:logout"  %}" class="btn btn-link">Salir</a></p>
          </div>
  	</div>


		<div class="row">
		  <div class="col-xs-2 col-md-2 col-sm-1">
		    <ul class="nav nav-pills nav-stacked">
			    <li><a href="{% url "appencuesta:encuesta_listar"  %}">Encuestas</a></li>
		    </ul>
		  </div>
		  <div class="col-xs-8 col-md-8 col-sm-4">
			{% block content %}{% endblock content %}
		  </div>
		</div>
	</body>
</html>